### ISSUE TITLE
[BUG] A trigger has to have at least one default value for conditions or no conditions will show in the UI.

### ISSUE THREAD

**Issue by calvinalkan** [FluentCRM/fluent-crm#10]
This is a javascript related issue. But since JS is minified I have no way to debug. 

To replicate the issue do the following. 

1. Comment out all the default values of the UserLoginTrigger (or any other trigger).
  ```php
  
   public function getFunnelConditionDefaults($funnel)
      {
          return [
              //'update_type'  => 'update', // skip_all_actions, skip_update_if_exist
              //'user_roles'   => [],
              //'run_multiple'       => 'yes'
          ];
      }
  
  ```
1. Create a funnel the trigger.
3. See that all conditional fields are gone.
4. Add the following dummy data: 

```php

 public function getFunnelConditionDefaults($funnel)
    {
        return [
            'foo' => 'bar'
            //'update_type'  => 'update', // skip_all_actions, skip_update_if_exist
            //'user_roles'   => [],
            //'run_multiple'       => 'yes'
        ];
    }
```
5. Create the funnel again and now everything is working. 

The same issue probably happens with settings fields and the reason most probably is that inside `BaseTrigger.php`

the default values are always serialized with `wp_parse_args` which does not give the desired result for an empty array.

```php

 public function prepareEditorDetails($funnel)
    {
        $funnel->settings = wp_parse_args($funnel->settings, $this->getFunnelSettingsDefaults());
        $funnel->settingsFields = $this->getSettingsFields($funnel);
        $funnel->conditions = wp_parse_args($funnel->conditions, $this->getFunnelConditionDefaults($funnel));
        $funnel->conditionFields = $this->getConditionFields($funnel);
        return $funnel;
    }

```

**Comment by techjewel** [comment]
Hello @calvinalkan
 Thanks for the insight. Basically, we use a custom-made form builder from JSON data in our Javascript and it checks if the default settings are empty or not. If not empty then we initiate the form builder. So in that case, If no defaults is given then it will not work. As you see, We always provide a default array in `getFunnelConditionDefaults()` method if we need a condition in the funnel.

So I think we don't need to change anything. But please reopen if you think otherwise :)
